---
abstract: 'Create and Read Zip Archives'
author:
  - 'Paul Marquess <pmqs@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.24, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Archive-Zip-SimpleZip
no_index:
  directory:
    - t
    - inc
    - t
    - private
requires:
  IO::Compress::Base: '2.08'
version: '0.020'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
