---
abstract: 'Read and Write Zip Archives'
author:
  - 'Paul Marquess <pmqs@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.34, CPAN::Meta::Converter version 2.150005'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Archive-Zip-SimpleZip
no_index:
  directory:
    - t
    - inc
    - t
    - private
recommends:
  IO::Compress::Lzma: '2.213'
  IO::Uncompress::UnLzma: '2.213'
  IO::Compress::Xz: '2.213'
  IO::Uncompress::UnXz: '2.213'
  IO::Compress::Zstd: '2.213'
  IO::Uncompress::UnZstd: '2.213'
  IO::Compress::Bzip2: '2.213'
  IO::Uncompress::Bunzip2: '2.213'
requires:
  IO::Compress::Base: '2.213'
  IO::Uncompress::Base: '2.213'
  IO::Compress::Zip: '2.213'
  IO::Uncompress::Unzip: '2.213'
  IO::Compress::RawDeflate: '2.213'
  IO::Uncompress::RawInflate: '2.213'
  Perl::OSType: '0'
resources:
  bugtracker: https://github.com/pmqs/Archive-Zip-SimpleZip/issues
  homepage: https://github.com/pmqs/Archive-Zip-SimpleZip
  repository: git://github.com/pmqs/Archive-Zip-SimpleZip.git
version: '1.001'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
